
# Loads default set of integrations. Do not remove.
default_config:

light:
  - platform: soundcraftui
    name: "Soundcraft UI"
    mac: "D8:71:4D:31:09:68"
python_script:# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
